/**
 * Role of a chat message sender
 * - "user"      → message sent by the user
 * - "assistant" → message generated by AI
 */
export type Role = "user" | "assistant";

/**
 * Represents a single chat message
 */
export interface IMessage {
    isImage: boolean;        // Whether the message is an image response
    isPublished: boolean;    // Whether image is shared to community
    role: Role;              // Sender of the message
    content: string;         // Text message OR image URL
    timestamp: number;       // Unix timestamp (Date.now())
}

/**
 * Represents a chat conversation
 */
export interface IChat {
    _id: string;             // Chat ID from database
    userId: string;          // Owner user ID
    userName?: string;       // Optional username (used in community images)
    name: string;            // Chat display name
    messages: IMessage[];    // List of messages in the chat
    createdAt: string;       // Chat creation timestamp
    updatedAt: string;       // Last update timestamp
}

/**
 * Represents an authenticated user
 */
export interface IUser {
    _id: string;             // User ID
    name: string;            // Full name
    email: string;           // Email address
    credits: number;         // Remaining AI usage credits
}

/**
 * Represents a subscription / credit plan
 */
export interface IPlan {
    _id: string;             // Plan identifier (basic / pro / premium)
    name: string;            // Display name
    price: number;           // Price in USD
    credits: number;         // Credits provided by the plan
    features: string[];      // List of plan features
}

/**
 * Represents a published community image
 */
export interface IPublishedImage {
    imageUrl: string;        // Public ImageKit URL
    userName: string;        // Creator's name
}